echo "========================================="
echo "AGROGUARD HACKATHON DEMO"
echo "========================================="
echo ""
echo "1. Web interface: http://127.0.0.1:5000"
echo "2. Live feed: http://127.0.0.1:5000/live"
echo ""
echo "To test detection:"
echo "- Show armyworm image to camera"
echo "- Watch terminal for 'Classified: armyworm'"
echo "- Buzzer will sound (simulated)"
echo "- Event will be logged"
echo ""
echo "Press Ctrl+C to stop"
echo "========================================="
